swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Mini Blog"
  contact:
    name: "Lam Hoang"
    email: "hoanglam1699@gmail.com"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "books"
schemes:
- "http"

paths:

  /books:
    get:
      tags:
      - "books"
      summary: "Get books"
      description: ""
      operationId: "getBooks"
      produces:
      - "application/json"
      parameters:
        - name: "page"
          in: "query"
          description: ""
          required: true
          type: "integer"
          format: "int32"
        - name: "pageSize"
          in: "query"
          description: ""
          required: true
          type: "integer"
          format: "int32"
        - name: "sort"
          in: "query"
          description: ""
          required: true
          type: "string"
        - name: "colName"
          in: "query"
          description: ""
          required: true
          type: "string"
        - name: "search"
          in: "query"
          description: ""
          required: true
          type: "string"
      responses:
        "200":
          $ref: "#/responses/Books"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/NoAuthorized"
        "404":
          $ref: "#/responses/NotFound"
        "500":
          $ref: "#/responses/InternalServerError"
    post:
      tags: 
      - "books"
      summary: "Post books"
      description: ""
      operationId: "saveBook"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "request"
          description: "request"
          required: true
          schema:
            $ref: '#/definitions/BookReq'
      responses:
        "200":
          $ref: "#/responses/Book"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/NoAuthorized"
        "404":
          $ref: "#/responses/NotFound"
        "500":
          $ref: "#/responses/InternalServerError"
    delete:
      tags: 
      - "books"
      summary: "Delete books"
      description: ""
      operationId: "deleteBooks"
      produces:
      - "application/json"
      parameters:
        - name: "ids"
          in: "query"
          description: ""
          required: true
          type: "array"
          items:
            type: "integer"
            format: "int64"
      responses:
        "200":
          $ref: "#/responses/OK"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/NoAuthorized"
        "404":
          $ref: "#/responses/NotFound"
        "500":
          $ref: "#/responses/InternalServerError"
    
  /books/{bookId}:
    get:
      tags:
      - "books"
      summary: "Get book by Id"
      description: ""
      operationId: "getBookById"
      produces:
      - "application/json"
      parameters:
        - name: "bookId"
          in: "path"
          description: ""
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          $ref: "#/responses/Book"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/NoAuthorized"
        "404":
          $ref: "#/responses/NotFound"
        "500":
          $ref: "#/responses/InternalServerError"
    put:
      tags: 
      - "books"
      summary: "Put book"
      description: ""
      operationId: "updateBook"
      produces:
      - "application/json"
      parameters:
        - name: "bookId"
          in: "path"
          description: ""
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "request"
          description: "request"
          required: true
          schema:
            $ref: '#/definitions/BookReq'
      responses:
        "200":
          $ref: "#/responses/Book"
        "400":
          $ref: "#/responses/BadRequest"
        "401":
          $ref: "#/responses/NoAuthorized"
        "404":
          $ref: "#/responses/NotFound"
        "500":
          $ref: "#/responses/InternalServerError"
    
definitions:
  Book:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 10
      title:
        type: "string"
        example: "Travel book"
      description:
        type: "string"
        example: "Every day, more and more people want to learn some HTML and CSS."
      image:
        type: "string"
        example: "https://freepdf-books.com/doc-images/8275.png"
      category:
        type: "string"
        example: "music"
      createDate:
        type: "string"
        example: "10-03-2022"
      modifiedDate:
        type: "string"
        example: "10-03-2022"
        
  BookReq:
    type: "object"
    properties:
      title:
        type: "string"
        example: "Travel book"
      description:
        type: "string"
        example: "Every day, more and more people want to learn some HTML and CSS."
      image:
        type: "string"
        example: "https://freepdf-books.com/doc-images/8275.png"
      category:
        type: "string"
        example: "music"
      createDate:
        type: "string"
        example: "10-03-2022"
      modifiedDate:
        type: "string"
        example: "10-03-2022"
        
  Books:
    type : "object"
    properties:
      numPage:
        type: "integer"
        format: "int32"
        example: 10
      listBook:
        type: "array"
        items :
          $ref : "#/definitions/Book"
      
responses: 
  Book:
    description : 'Book Response'
    schema :
      $ref : '#/definitions/Book'
      
  Books:
    description : 'Books Response'
    schema :
      $ref : '#/definitions/Books'
      
  OK:
    description: '200: OK'
  Created:
    description: '201: Created'
  Accepted:
    description: '202: Accepted'
  NoContent:
    description: '204: NoContent'
  BadRequest:
    description: '400: Bad Request'
  NoAuthorized:
    description: '401: No Authorized'
  Forbidden:
    description: '403: Forbidden'
  NotFound:
    description: '404: Not Found'
  InternalServerError:
    description: '500: Internal Server Error'
    
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"